version: '3.8'

services:

  nginx:
    build:
      context: .
      dockerfile: dockerfile.nginx
    ports:
      - '80:80'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    environment:
      - node.name=quadzig-node
      - cluster.name=es-quadzig-cluster
      - discovery.type=single-node
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    env_file:
      - .env
#    networks:
#      - elastic

#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.12.1
#    environment:
#      - node.name=kibana-quadzig
#      - cluster.name=kib-quadzig-cluster
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - '5601:5601'
#    networks:
#      - elastic
#    depends_on:
#      - elasticsearch

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server #/quadzigg/config/initializers/redis.rb
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
     # - redis.conf:/quadzigg/config/initializers

  sidekiq:
    depends_on:
      - 'redis'
      - 'db'
      - 'elasticsearch'
    build:
      context: .
      dockerfile: dockerfile.bg
    volumes:
      - .:/myapp
    env_file:
      - .env

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: dockerfile.app
    environment:
      RAILS_ENV: development
      DB_USERNAME: quadzig
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: quadzig_development
    volumes:
      - .:/myapp
    depends_on:
      - db
      - sidekiq
      - redis
    ports:
      - '3000:3000'
    restart: on-failure:3
    env_file:
      - .env

volumes:
  data:
    driver: local
  myapp:
  postgres:
  redis:

#networks:
#  elastic:
#     driver: bridge
