version: '3.8'

services:

  nginx:
    build:
      context: .
      dockerfile: dockerfile.nginx
    ports:
      - '80:80'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
#      - xpack.security.enabled=false
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # Set JVM options
#      - http.host=0.0.0.0  # allow HTTP traffic fron local host 
#      - "ES_HTTP_CORS_ENABLE=true"  # Enable CORS
#      - "ES_HTTP_CORS_ALLOW_ORIGIN=*"
#      - "ES_JAVA_OPTS=-Dcom.sun.net.ssl.checkRevocation=false"  # Disable certificate revocation checks (if needed)
      # Add any other Elasticsearch settings here
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  sidekiq:
    depends_on:
      elasticsearch:
        condition: service_healthy
    build:
      context: .
      dockerfile: dockerfile.bg
    volumes:
      - .:/myapp
    env_file:
      - .env

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s


  web:
    build:
      context: .
      dockerfile: dockerfile.app
    environment:
      RAILS_ENV: development
      DB_USERNAME: quadzig
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: quadzig_development
    volumes:
      - .:/myapp
    depends_on:
      - db
      - sidekiq
      - redis
      - elasticsearch
    ports:
      - '3000:3000'
    restart: on-failure:3
    env_file:
      - .env

volumes:
  myapp:
  postgres:
  redis:
