---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template to provide secure access to Quadzig'
Parameters:
  ExternalId:
    Type: String
    Description: External ID unique to your AWS account.
  QuadzigAccountId:
    Type: String
    Description: The Account ID from where quadzig assumes this IAM Role

Resources:
  StackProgressNotification:
    Type: "Custom::RoleProvisionNotifier"
    Version: "1.0"
    Properties: 
      ServiceToken: !Sub "arn:aws:sns:${AWS::Region}:${QuadzigAccountId}:AccountAddSignalTopic-quadzig-production"
      RoleName: !GetAtt QuadzigRole.Arn
      AccountId: !Ref AWS::AccountId
      ExternalId: !Ref ExternalId
      StackName: !Ref AWS::StackName
      StackId: !Ref AWS::StackId
      RegionCode: !Ref AWS::Region
      IAMRoleVersion: "3"

  QuadzigRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        -
          PolicyName: "QuadzigAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "autoscaling:DescribeAutoScalingGroups"
                  - "cloudtrail:DescribeTrails"
                  - "cloudwatch:GetMetricData"
                  - "ec2:DescribeAddresses"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeClientVpnConnections"
                  - "ec2:DescribeClientVpnEndpoints"
                  - "ec2:DescribeClientVpnRoutes"
                  - "ec2:DescribeInstances"
                  - "ec2:DescribeInternetGateways"
                  - "ec2:DescribeNatGateways"
                  - "ec2:DescribeNetworkAcls"
                  - "ec2:DescribeRouteTables"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeSpotFleetInstances"
                  - "ec2:DescribeSpotFleetRequests"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeTags"
                  - "ec2:DescribeTransitGatewayAttachments"
                  - "ec2:DescribeTransitGatewayPeeringAttachments"
                  - "ec2:DescribeTransitGatewayRouteTables"
                  - "ec2:DescribeTransitGateways"
                  - "ec2:DescribeTransitGatewayVpcAttachments"
                  - "ec2:DescribeVolumes"
                  - "ec2:DescribeVpcPeeringConnections"
                  - "ec2:DescribeVpcs"
                  - "ec2:DescribeVpnConnections"
                  - "ec2:DescribeVpnGateways"
                  - "ecs:DescribeClusters"
                  - "ecs:DescribeContainerInstances"
                  - "ecs:DescribeServices"
                  - "ecs:ListClusters"
                  - "ecs:ListContainerInstances"
                  - "ecs:ListServices"
                  - "ecs:ListTagsForResource"
                  - "eks:DescribeNodegroup"
                  - "eks:ListClusters"
                  - "eks:DescribeCluster"
                  - "eks:ListNodegroups"
                  - "elasticache:DescribeCacheClusters"
                  - "elasticache:DescribeCacheSecurityGroups"
                  - "elasticache:DescribeCacheSubnetGroups"
                  - "elasticache:DescribeGlobalReplicationGroups"
                  - "elasticache:DescribeReplicationGroups"
                  - "elasticache:ListTagsForResource"
                  - "elasticfilesystem:DescribeFileSystems"
                  - "elasticloadbalancing:DescribeInstanceHealth"
                  - "elasticloadbalancing:DescribeLoadBalancerAttributes"
                  - "elasticloadbalancing:DescribeLoadBalancerPolicies"
                  - "elasticloadbalancing:DescribeLoadBalancerPolicyTypes"
                  - "elasticloadbalancing:DescribeLoadBalancers"
                  - "elasticloadbalancing:DescribeTags"
                  - "es:DescribeElasticsearchDomains"
                  - "kafka:ListClusters"
                  - "lambda:ListFunctions"
                  - "rds:DescribeDBClusters"
                  - "rds:DescribeDBInstances"
                  - "rds:DescribeDBSubnetGroups"
                  - "rds:ListTagsForResource"
                  - "redshift:DescribeClusters"
                Resource: "*"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: 
            "AWS": !Join [ "", [ "arn:aws:iam::", !Ref QuadzigAccountId, !Sub ':role/quadzig-production-CrossAccountAccessRole' ] ]
          Action:
          - sts:AssumeRole
          Condition:
            StringEquals:
              'sts:ExternalId': !Ref ExternalId

Outputs:
  IAMRoleArn:
    Value: !GetAtt QuadzigRole.Arn
  ExternalId:
    Value: !Ref ExternalId